### PR TITLE
Feature/homework

### PR DESCRIPTION
**Pull request by johnzer123**
[](url
[TST_Data_Template.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7705277/TST_Data_Template.xls)
[TST_Data_Readme.md](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7705278/TST_Data_Readme.md)
)

### CODE REVIEW

**Comment by johnzer123** [comment]
My test data.

[TST_Wang_2020-12_QS.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7714665/TST_Wang_2020-12_QS.zip)

**Comment by johnzer123** [comment]
Final version of Metadata template

[TST_Data_Template.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7714690/TST_Data_Template.xls)

**Comment by johnzer123** [comment]
My test data files

[TST_Wang_2020-12_QS.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7714709/TST_Wang_2020-12_QS.zip)

**Comment by sbancal** [comment]
Je ferme cette PR.
Bonne suite à vous.

**Pull request closed without merging**
