### PR TITLE
Update TST_Data_Convention.md

### PR DESCRIPTION
**Pull request by vsdharun**

### CODE REVIEW

**Comment by sbancal** [comment]
I don't understand the possible impact of `Multiple measurement points = y` .
Are there any ?

**Comment by vsdharun** [comment]
> I don't understand the possible impact of `Multiple measurement points = y` . Are there any ?

Yes, For example- In Conzgzhe's experiments , the deflection will be measured from multiple points and their location need to be mentioned.

**Comment by sbancal** [comment]
I see. `#` is always replaced by an integer, as it is in https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960222/TST_2021-11_QS_002.csv

**Comment by sbancal** [comment]
This is now documented in https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/b2d4a02646a313ecc085a6d03791a1bcdf49b879/Data/TST_Data_Convention.md

Please check that it matches what you expect and if needed, open an Issue on it.

I close this Pull Request as it's now implemented.

**Pull request closed without merging**
