### PR TITLE
Create TST_Vahedi_2022_8_FI

### PR DESCRIPTION
**Pull request by NiloufarV**
I want to create the file for uploading the data base of my PhD project.

### CODE REVIEW

**Comment by NiloufarV** [comment]
[Shear-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445606/Shear-TST_Data_Template_20.AUG.2022.xlsx)
[Tensile-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445607/Tensile-TST_Data_Template_20.AUG.2022.xlsx)
[Thermal elongation-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445608/Thermal.elongation-TST_Data_Template_20.AUG.2022.xlsx)
[Compressive-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445609/Compressive-TST_Data_Template_20.AUG.2022.xlsx)
[Pure balsa-TST_Data_Template_18 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445613/Pure.balsa-TST_Data_Template_18.AUG.2022.xlsx)
[TGA-TST_Data_Template_19 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445614/TGA-TST_Data_Template_19.AUG.2022.xlsx)

**Comment by NiloufarV** [comment]
[B4-TST_Data_Template_23 AUG 2022.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445631/B4-TST_Data_Template_23.AUG.2022.xls)
[small specimens-TST_Data_Template_21 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445633/small.specimens-TST_Data_Template_21.AUG.2022.xlsx)
[Pure balsa-TST_Data_Template_18 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445636/Pure.balsa-TST_Data_Template_18.AUG.2022.xlsx)

**Comment by NiloufarV** [comment]
[Tensile-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445639/Tensile-TST_Data_Template_20.AUG.2022.xlsx)
[Thermal elongation-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445640/Thermal.elongation-TST_Data_Template_20.AUG.2022.xlsx)
[Compressive-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445641/Compressive-TST_Data_Template_20.AUG.2022.xlsx)
[Shear-TST_Data_Template_20 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445642/Shear-TST_Data_Template_20.AUG.2022.xlsx)
[TGA-TST_Data_Template_19 AUG 2022.xlsx](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9445643/TGA-TST_Data_Template_19.AUG.2022.xlsx)

**Comment by sbancal** [comment]
Dear @NiloufarV ,

Thank you for these files you sent.
In order to process your datasets, please refer to the Data convention described [here](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/3acc1f55951b8df2c3c2c94c5bce59b512c796a1/Data/TST_Data_Convention.md)

Basicaly : 
1 dataset = 1 zip file with :
- 1 xls file with 2 tabs. template is available [here](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/4e03de11eb80e8befc0315006568d3734ca50c90/Data/TST_Data_Template.xls?raw=true)
- several csv files (expected columns are described on TST_Data_Convention.md linked above.

Once you have prepared 1 dataset, please send it [here](https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/new?assignees=sbancal&labels=Dataset%2Ctriage&template=dataset_integration_request.yml&title=%5BNew+Dataset%5D+%3A+%7B3LettersDataCode%7D_%7BResearcher%27s+lastname%7D_%7BDate%7D_%7BTest+type%7D). We expect 1 issue per dataset.

In the meantime, I'm preparing the dataset checker web page.I expect to deploy it in a few days. I'll let you know as soon as it's ready.

**Comment by sbancal** [comment]
Dear @NiloufarV ,

The dataset checker is now available [here](https://ccfatigue-test.epfl.ch/fatigue_database/data_upload) .
Please use it and follow the instructions on in order to integrate your datas. 

Regards,
Samuel

**Pull request closed without merging**
