### PR TITLE
TST_Wang_2021-11_QS

### PR DESCRIPTION
**Pull request by johnzer123**
[TST_2021-11_QS_001.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906114/TST_2021-11_QS_001.csv)
[TST_2021-11_QS_002.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906115/TST_2021-11_QS_002.csv)
[TST_2021-11_QS_003.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906116/TST_2021-11_QS_003.csv)
[TST_2021-11_QS_004.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906117/TST_2021-11_QS_004.csv)
[TST_2021-11_QS_005.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906118/TST_2021-11_QS_005.csv)
[TST_2021-11_QS_metadata.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906119/TST_2021-11_QS_metadata.xls)

### CODE REVIEW

**Comment by johnzer123** [comment]
[TST_Data_Readme.md](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906125/TST_Data_Readme.md)

**Comment by johnzer123** [comment]
[TST_Data_Readme.md](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906343/TST_Data_Readme.md)

**Comment by johnzer123** [comment]
[TST_Data_Readme.md](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/7906481/TST_Data_Readme.md)

**Comment by sbancal** [comment]
I guess this is now a duplicate with https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/51
So I close it and will answer on the other one.

**Pull request closed without merging**
