### PR TITLE
Create TST_Wang_2020-12_QS

### PR DESCRIPTION
**Pull request by johnzer123**
[TST_2020-12_QS_002.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960183/TST_2020-12_QS_002.csv)
[TST_2020-12_QS_003.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960184/TST_2020-12_QS_003.csv)
[TST_2020-12_QS_metadata.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960185/TST_2020-12_QS_metadata.xls)
[TST_2020-12_QS_004.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960186/TST_2020-12_QS_004.csv)
[TST_2020-12_QS_001.csv](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/8960187/TST_2020-12_QS_001.csv)

### CODE REVIEW

**Comment by johnzer123** [comment]
> Hi,
> 
> It's not possible to integrate these data as is. As specified in https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/feat/data-validation/Data/TST_Data_Convention.md#tst-csv-files-standards-column-names-must-be-exact- , `Machine_Time` is expected to be of **Integer type**. Here it looks to be in the format of `hour-minutes-seconds` : `'17:25:46'`.

Hello,

I didn't notice the data type. But the `Machine_Time` and `Th_time` should be either **Double** or in hh:mm:ss.00 (ss in Double precision). Also we missed a column `MD_time`, whose type also be **Double** or hh:mm:ss.00. 
Could you update these changes? 
Seems there were some mistakes from our side. I am sorry for that. But these changes have been agreed among us for a long time. I don't know why we didn't include these in the last convention file...

**Comment by sbancal** [comment]
Hi @johnzer123 ,

You speak of a new column called `MD_time`.
If I look at the current convention : https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/feat/data-validation/Data/TST_Data_Convention.md#tst-csv-files-standards-column-names-must-be-exact-
all `MD_*` columns finish with `--#`.

Can you confirm you want `MD_time`, not `MD_time--#` ?

**Comment by sbancal** [comment]
And what Description will I put for that column ?

I guess it's not a mandatory column ?

**Comment by sbancal** [comment]
Dear @johnzer123 ,
your dataset `TST_Wang_2020-12_QS` has been successfuly preprocessed.

Regards,
Samuel

**Pull request closed without merging**
